### ISSUE TITLE
Thumb over the range slider

### ISSUE THREAD

**Issue by gmcusaro** [spacenation/swiftui-sliders#39]
Range `0.0 ... 1.0` Very simple. As the title with a value beyond the range the thumb goes beyond. Here a comparison with system sliders that stops at the end. Problem found only with MacOS Monterey Beta 6 (21A5506J).

In addition the `Resources` and` Examples` folders in Package are missing.

<img width="1740" alt="range" src="https://user-images.githubusercontent.com/30832514/132685708-4b8d68cd-d750-4269-89b4-aeb690cd84c1.png">

[slider-range-bug.swift.zip](https://github.com/spacenation/swiftui-sliders/files/7136461/slider-range-bug.swift.zip)

**Comment by ay42** [comment]
@gmcusaro Thank you for your feedback.
