### ISSUE TITLE
Track colors 

### ISSUE THREAD

**Issue by gemiren** [spacenation/swiftui-sliders#51]
First of all, thanks for the awesome library. Would love to see more examples of usage. I'm trying to set different track colors for active (left of thumb) and inactive (right of the thumb) parts. How can I do that?  Any help is appreciated.

**Comment by ay42** [comment]
@gemiren
```swift
ValueSlider(value: $value5)
    .valueSliderStyle(
        HorizontalValueSliderStyle(
            track:
                HorizontalTrack(view: Color.blue)
                    .frame(height: 3)
                    .background(Color.red)
                    .cornerRadius(1.5)
        )
    )
```
<img width="576" alt="Screen Shot 2022-04-17 at 9 14 26 AM" src="https://user-images.githubusercontent.com/2933241/163723084-5814c448-6580-4aed-ac34-f9b84b82b171.png">

I also added your example to the project here 538e16b35ad7a066a8f5624da9ecee6327886bf7

**Comment by gemiren** [comment]
Perfect! Thanks very much for the example.
