### ISSUE TITLE
How to specify a minimum selectable range for HRangeSlider?

### ISSUE THREAD

**Issue by skryshi** [spacenation/swiftui-sliders#6]
Hi. First of all, thank you for an awesome library!

A quick question:
How do I specify a minimum selectable range for an HRangeSlider? Couldn't find it in the options.

**Comment by ay42** [comment]
Hi @skryshi 
Sorry about answering so late.
There is no way to do it right now, but this is something I should definitely do.
I'll keep you posted here on the progress
